### PR TITLE
Fix DRF permissions and nested elements

### PR DESCRIPTION
**Pull request by GuzekAlan**

### CODE REVIEW

**Review by piotrekg35 — COMMENTED** [review]
Please update also devicemanager/fixtures/inventory.yaml. Line 110, rename model to device_model.

**Review by piotrekg35 — COMMENTED** [review]
Are you sure this works? Because as I login with my google account (no permissions) I am still able to get /inventory/rooms data.

**Comment by Critteros** [comment]
image

**Comment by Critteros** [comment]
Domyśle DjangoModelPermissions mapuje tak permissiony

```py
class DjangoModelPermissions(BasePermission):
    """
    The request is authenticated using `django.contrib.auth` permissions.
    See: https://docs.djangoproject.com/en/dev/topics/auth/#permissions

    It ensures that the user is authenticated, and has the appropriate
    `add`/`change`/`delete` permissions on the model.

    This permission can only be applied against view classes that
    provide a `.queryset` attribute.
    """

    # Map methods into required permission codes.
    # Override this if you need to also provide 'view' permissions,
    # or if you want to provide custom permission codes.
    perms_map = {
        'GET': [],
        'OPTIONS': [],
        'HEAD': [],
        'POST': ['%(app_label)s.add_%(model_name)s'],
        'PUT': ['%(app_label)s.change_%(model_name)s'],
        'PATCH': ['%(app_label)s.change_%(model_name)s'],
        'DELETE': ['%(app_label)s.delete_%(model_name)s'],
    }
  ```
  
  
   Trzeba nadpisać dla GET aby korzystało z read permission

**Review by Critteros — APPROVED** [review]

**Pull request merged**
